requests:
  selectAll: "SELECT * FROM userTable"
  selectUser: "SELECT * FROM userTable WHERE id=?"
  saveUser: "INSERT INTO userTable VALUES (DEFAULT, ?, ?)"
  deleteUser: "DELETE FROM userTable WHERE id=?"
  updateUser: "UPDATE userTable SET firstName=?, lastName=? WHERE id=?"

